name: Debug Original Script
on:
  workflow_dispatch:
  
jobs:
  debug-script:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandoc-latex-environment
          pip install weasyprint
          sudo apt-get update
          sudo apt-get install -y pandoc
      
      - name: Create test directory
        run: |
          mkdir -p test-z60
          echo "# 测试手册" > test-z60/README.md
          echo "[测试章节](test-chapter.md)" >> test-z60/README.md
          echo "# 测试章节" > test-z60/test-chapter.md
          echo "这是一个测试内容。" >> test-z60/test-chapter.md
      
      - name: Create output directory
        run: mkdir -p pdf-output
      
      - name: Show original script content
        run: |
          echo "Original script content:"
          cat .github/scripts/generate_pdf.py
      
      - name: Run script with debug
        run: |
          # Run with Python debugger to get traceback
          python -m pdb -c "cont; quit" .github/scripts/generate_pdf.py --dir test-z60 --output pdf-output --css styles/default.css --author "Z-Series" || true
          
          # Additional debugging output
          echo "Directory structure:"
          find test-z60 -type f | sort
          echo "Python version:"
          python --version
