name: Generate PDF Manuals

on:
  workflow_dispatch:
    inputs:
      manual_path:
        description: 'Path to the manual directory (e.g., ZSeries/Z60)'
        required: true

jobs:
  build-pdfs:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout repository (full)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 获取完整历史记录以解决图片路径问题

      - name: Setup environment
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            pandoc \
            libpango-1.0-0 \
            libharfbuzz-dev \
            fonts-noto-cjk \
            fontconfig
          echo "=== Font verification ==="
          fc-list :lang=zh | grep Noto

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install \
            weasyprint==58.1 \  # 使用稳定版本避免TypeError
            pandoc-latex-environment

      - name: Prepare directories
        run: |
          mkdir -p pdf-output
          # 创建带图片路径修复的CSS
          cat << 'EOF' > .github/styles/default.css
          body {
            font-family: "Noto Sans CJK SC", sans-serif;
            font-size: 11pt;
            line-height: 1.5;
          }
          img {
            max-width: 100%;
            height: auto;
          }
          EOF

      - name: Generate PDF (with image path fix)
        env:
          FONTCONFIG_PATH: /etc/fonts
          PYTHONPATH: ${{ github.workspace }}
        run: |
          set -ex
          echo "=== Generating PDF with image path handling ==="
          
          # 临时修复图片路径
          python .github/scripts/generate_pdf.py \
            --dir "${{ github.event.inputs.manual_path }}" \
            --output pdf-output \
            --css "$(pwd)/.github/styles/default.css" \
            --author "Your-Company-Name" \
            --image-root "$(pwd)" \  # 添加图片根路径参数
            --verbose || {
              echo "=== Fallback to xelatex ==="
              pandoc "${{ github.event.inputs.manual_path }}/README.md" -o pdf-output/fallback.pdf \
                --pdf-engine=xelatex \
                -V mainfont="Noto Sans CJK SC"
            }

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: manual-${{ github.event.inputs.manual_path | replace('/', '-') }}
          path: pdf-output/*.pdf
          retention-days: 30
