name: Minimal Python Test
on:
  workflow_dispatch:
  
jobs:
  test-minimal:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
      
      - name: Run minimal Python script
        run: |
          python -c "
          print('Hello from Python')
          print('Current directory:', __import__('os').getcwd())
          print('Python version:', __import__('sys').version)
          with open('test.txt', 'w') as f:
              f.write('Test content')
          print('File created successfully')
          "
      
      - name: Verify file creation
        run: |
          ls -la test.txt
          cat test.txt
