name: Modified Script Test
on:
  workflow_dispatch:
  
jobs:
  modified-script:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandoc-latex-environment
          pip install weasyprint
          sudo apt-get update
          sudo apt-get install -y pandoc
      
      - name: Create test directory
        run: |
          mkdir -p test-z60
          echo "# 测试手册" > test-z60/README.md
          echo "[测试章节](test-chapter.md)" >> test-z60/README.md
          echo "# 测试章节" > test-z60/test-chapter.md
          echo "这是一个测试内容。" >> test-z60/test-chapter.md
      
      - name: Create output directory
        run: mkdir -p pdf-output
      
      - name: Create modified script
        run: |
          # Copy the original script
          cp .github/scripts/generate_pdf.py modified_script.py
          
          # Add try-except wrapper around the main function call
          cat >> modified_script.py << 'EOF'

# Add try-except wrapper to the end of the file
if __name__ == "__main__":
    try:
        main()
    except Exception as e:
        import traceback
        print("Error occurred:", str(e))
        traceback.print_exc()
        # Continue instead of exiting with error
        print("Continuing despite error...")
        exit(0)
EOF
      
      - name: Run modified script
        run: |
          python modified_script.py --dir test-z60 --output pdf-output --css styles/default.css --author "Z-Series"
          
          echo "Output directory content:"
          ls -la pdf-output/ || echo "No output directory"
      
      - name: Upload any generated files
        uses: actions/upload-artifact@v4
        with:
          name: modified-script-output
          path: pdf-output/*.pdf
          if-no-files-found: warn
