name: Original Script Test
on:
  workflow_dispatch:
  
jobs:
  test-original-script:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandoc-latex-environment
          pip install weasyprint
          sudo apt-get update
          sudo apt-get install -y pandoc
      
      - name: Create test directory structure
        run: |
          # Create test directory
          mkdir -p test-z60
          
          # Create README.md with link
          cat > test-z60/README.md << 'EOF'
          # 测试手册
          
          [测试章节](test-chapter.md)
          EOF
          
          # Create linked file
          cat > test-z60/test-chapter.md << 'EOF'
          # 测试章节
          
          这是一个测试内容。
          EOF
          
          # Create CSS file if not exists
          mkdir -p styles
          if [ ! -f styles/default.css ]; then
            cat > styles/default.css << 'EOF'
            body {
                font-family: "Noto Sans CJK SC", "SimSun", sans-serif;
                font-size: 11pt;
                line-height: 1.5;
            }
            h1 {
                color: #1a73e8;
            }
            EOF
          fi
      
      - name: Create output directory
        run: mkdir -p pdf-output
      
      - name: Run original Python script with test directory
        run: |
          # Use the original script but with the test directory
          python .github/scripts/generate_pdf.py --dir test-z60 --output pdf-output --css styles/default.css --author "Z-Series"
          
          # Show the output directory content
          ls -la pdf-output/
      
      - name: Upload generated PDF
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: original-script-test-pdf
          path: pdf-output/*.pdf
