name: PDF Dependencies Test
on:
  workflow_dispatch:
  
jobs:
  test-dependencies:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install weasyprint
          sudo apt-get update
          sudo apt-get install -y pandoc
          
          # Verify installations
          python -c "import weasyprint; print('WeasyPrint version:', weasyprint.__version__)"
          pandoc --version
      
      - name: Create test markdown
        run: |
          echo "# Test Document" > test.md
          echo "This is a simple test." >> test.md
      
      - name: Generate PDF with pandoc
        run: |
          pandoc test.md -o test.pdf --pdf-engine=weasyprint
          ls -la test.pdf
          du -h test.pdf
      
      - name: Upload test PDF
        uses: actions/upload-artifact@v4
        with:
          name: pandoc-test-pdf
          path: test.pdf
